### ISSUE TITLE
Persist counter values

### ISSUE THREAD

**Issue by HLXEasy** [lyokha/nginx-custom-counters-module#1]
As I need a download counter for nginx, I've found this promising module. But a hard requirement is that the counter values must be stored. It's a must that they not get lost let's say during a reboot. So is there a way to achieve this with this module?

Other ideas would also be welcome of course. Thx a lot in advance!

**Comment by lyokha** [comment]
Counters can survive between reloads of nginx: see https://github.com/lyokha/nginx-custom-counters-module#reloading-nginx-configuration. However they cannot survive between machine reboot as they are not stored on a disk.

If you want to save them between reboots, you have to implement some hook on nginx' exit. There is no standard way for doing so, however I have another module: https://github.com/lyokha/nginx-haskell-module, that is capable of doing so, however it requires writing a bit of Haskell code.

**Comment by lyokha** [comment]
@HLXEasy, you can try [this](https://github.com/lyokha/nginx-custom-counters-module#persistent-counters)

**Comment by HLXEasy** [comment]
Wow, awesome! Will definately try this. Thx a lot in advance.

**Comment by HLXEasy** [comment]
Works like a charm! Very nice, thx. So ready for the next release. 💯

**Comment by lyokha** [comment]
The current solution is not protected against power outage. Counters are saved only upon Nginx master process' exit. Writing file on every counter's update would inevitably kill Nginx performance. The workaround could be writing backup files periodically (not implemented, backup files must not be of the same path as the persistent storage), or inspecting variable `$cnt_collection` in a user requests periodically and writing the responses into a backup file (this can be done right now, backup files have the same format as the variable's value). However, in both workarounds there is possibility of losing a bit of counter updates that could happen between the last check and the start of the power outage.

**Comment by lyokha** [comment]
Backups implemented, see updated docs.
